
# this config file contains all config fields with comments
kind: Cluster
apiVersion: kind.sigs.k8s.io/v1alpha3
# patch the generated kubeadm config with some extra settings
kubeadmConfigPatches:
- |
  apiVersion: kubeadm.k8s.io/v1beta2
  kind: InitConfiguration
  metadata:
    name: config
  apiServer:
    extraArgs:
      # Don't forget quotes on the values
      insecure-bind-address: "0.0.0.0"
      insecure-port: "8080"
  etcd:
    local:
      extraArgs:
        # Don't forget quotes on values
        client-cert-auth: "false"
  nodeRegistration:
    kubeletExtraArgs:
      # These two allow for unauthenticated kubelet access
      authorization-mode: "AlwaysAllow"
      anonymous-auth: "true"
# 1 control plane node and 3 workers
nodes:
# the control plane node config
- role: control-plane
  extraPortMappings:
    - containerPort: 8080
      hostPort: 8080
